package com.byazt.vfu;

import android.R;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.StateListDrawable;
import android.text.TextUtils;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.byazt.ff.FlowLayout;
import com.byazt.ff.TTDislikeCommentLayout;
import com.byazt.ff.TTDislikeLayout;
import com.byazt.ff.TTDislikeScrollListView;
import com.byazt.nr.eo;
import com.byazt.nr.z;
import com.bykv.vk.component.ttvideo.player.MediaPlayer;

/* JADX INFO: loaded from: classes2.dex */
@com.byazt.zqa.c(c = {0, 1, MediaPlayer.MEDIA_PLAYER_OPTION_STOP_SOURCE_ASYNC, 15})
public class uj {
    public static View c(final Context context, boolean z) {
        ScrollView scrollView = new ScrollView(context);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(-1, -1);
        layoutParams.setMargins(eo.c(context, 20.0f), 0, eo.c(context, 20.0f), 0);
        scrollView.setLayoutParams(layoutParams);
        GradientDrawable gradientDrawable = new GradientDrawable();
        gradientDrawable.setShape(0);
        gradientDrawable.setColor(-1);
        gradientDrawable.setCornerRadius(eo.c(context, 8.0f));
        scrollView.setBackground(gradientDrawable);
        scrollView.setPadding(eo.c(context, 16.0f), eo.c(context, 0.5f), eo.c(context, 16.0f), eo.c(context, 12.0f));
        TTDislikeLayout tTDislikeLayout = new TTDislikeLayout(context);
        tTDislikeLayout.setId(2047279103);
        tTDislikeLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
        tTDislikeLayout.setOrientation(1);
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setId(2047279102);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-1, -2);
        layoutParams2.setMargins(0, eo.c(context, 11.5f), 0, 0);
        linearLayout.setLayoutParams(layoutParams2);
        linearLayout.setOrientation(1);
        linearLayout.setVisibility(8);
        LinearLayout linearLayout2 = new LinearLayout(context);
        linearLayout2.setId(2047279101);
        linearLayout2.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
        linearLayout2.setGravity(16);
        linearLayout2.setOrientation(0);
        TextView textView = new TextView(context);
        textView.setId(2047279100);
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(0, -2);
        layoutParams3.weight = 1.0f;
        textView.setLayoutParams(layoutParams3);
        textView.setTextColor(Color.parseColor("#161823"));
        textView.setTextSize(2, 15.0f);
        textView.setTypeface(Typeface.DEFAULT);
        linearLayout2.addView(textView);
        ImageView imageView = new ImageView(context);
        imageView.setId(2047279099);
        imageView.setLayoutParams(new LinearLayout.LayoutParams(eo.c(context, 20.0f), -2));
        z.c(context, "tt_right_arrow", imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        linearLayout2.addView(imageView);
        linearLayout.addView(linearLayout2);
        View view = new View(context);
        view.setId(2047279098);
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(-1, eo.c(context, 0.5f));
        layoutParams4.setMargins(0, eo.c(context, 6.0f), 0, 0);
        view.setLayoutParams(layoutParams4);
        view.setBackgroundColor(Color.parseColor("#0F161823"));
        linearLayout.addView(view);
        tTDislikeLayout.addView(linearLayout);
        TTDislikeScrollListView tTDislikeScrollListView = new TTDislikeScrollListView(context);
        tTDislikeScrollListView.setId(2047279097);
        tTDislikeScrollListView.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
        tTDislikeScrollListView.setDivider(new ColorDrawable(Color.parseColor("#0F161823")));
        tTDislikeScrollListView.setDividerHeight(eo.c(context, 0.5f));
        tTDislikeScrollListView.setSelector(new ColorDrawable(0));
        tTDislikeScrollListView.setVerticalScrollBarEnabled(false);
        tTDislikeLayout.addView(tTDislikeScrollListView);
        View view2 = new View(context);
        view2.setId(2047279096);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(-1, eo.c(context, 0.5f));
        layoutParams5.setMargins(eo.c(context, 4.0f), eo.c(context, 6.0f), eo.c(context, 4.0f), eo.c(context, 11.5f));
        view2.setLayoutParams(layoutParams5);
        view2.setBackgroundColor(Color.parseColor("#0F161823"));
        view2.setVisibility(0);
        if (!z) {
            tTDislikeLayout.addView(view2);
            final TextView textView2 = new TextView(context);
            textView2.setId(2047279095);
            textView2.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
            GradientDrawable gradientDrawable2 = new GradientDrawable();
            gradientDrawable2.setColor(Color.parseColor("#FFFFFF"));
            gradientDrawable2.setCornerRadius(eo.c(context, 4.0f));
            gradientDrawable2.setStroke(eo.c(context, 1.0f), Color.parseColor("#0F161823"));
            textView2.setBackground(gradientDrawable2);
            z.c(context, "tt_suggestion_logo", new com.byazt.qr.c<Bitmap>() { // from class: com.byazt.vfu.uj.1
                @Override // com.byazt.qr.c
                public void c(Bitmap bitmap) {
                    textView2.setCompoundDrawablesWithIntrinsicBounds(new BitmapDrawable(context.getResources(), bitmap), (Drawable) null, (Drawable) null, (Drawable) null);
                }
            }, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
            textView2.setFocusable(false);
            textView2.setHint(" 其他建议");
            textView2.setPadding(eo.c(context, 8.6f), eo.c(context, 10.0f), 0, eo.c(context, 10.0f));
            textView2.setHintTextColor(Color.parseColor("#80161823"));
            textView2.setTextSize(2, 12.0f);
            textView2.setVisibility(0);
            tTDislikeLayout.addView(textView2);
        }
        scrollView.addView(tTDislikeLayout);
        return scrollView;
    }

    public static View tt(Context context, boolean z) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
        linearLayout.setOrientation(1);
        GradientDrawable gradientDrawable = new GradientDrawable();
        gradientDrawable.setShape(0);
        gradientDrawable.setColor(-1);
        gradientDrawable.setCornerRadius(eo.c(context, 2.0f));
        linearLayout.setBackground(gradientDrawable);
        if (z) {
            LinearLayout linearLayout2 = new LinearLayout(context);
            linearLayout2.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
            linearLayout2.setOrientation(0);
            ImageView imageView = new ImageView(context);
            imageView.setId(2047279093);
            LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(eo.c(context, 20.0f), eo.c(context, 20.0f));
            layoutParams.gravity = 16;
            layoutParams.setMargins(0, eo.c(context, 11.5f), eo.c(context, 12.0f), eo.c(context, 12.0f));
            imageView.setLayoutParams(layoutParams);
            linearLayout2.addView(imageView);
            TextView textView = new TextView(context);
            textView.setId(2047279094);
            LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-1, -2);
            layoutParams2.gravity = 16;
            layoutParams2.setMargins(0, eo.c(context, 11.5f), 0, eo.c(context, 12.0f));
            textView.setGravity(48);
            textView.setTextColor(Color.parseColor("#161823"));
            textView.setTextSize(2, 15.0f);
            textView.setTypeface(Typeface.DEFAULT);
            linearLayout2.addView(textView, layoutParams2);
            linearLayout.addView(linearLayout2);
        } else {
            TextView textView2 = new TextView(context);
            textView2.setId(2047279094);
            LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-1, -2);
            layoutParams3.gravity = 17;
            layoutParams3.setMargins(0, eo.c(context, 11.5f), 0, eo.c(context, 12.0f));
            textView2.setGravity(48);
            textView2.setTextColor(Color.parseColor("#161823"));
            textView2.setTextSize(2, 15.0f);
            textView2.setTypeface(Typeface.DEFAULT);
            linearLayout.addView(textView2, layoutParams3);
        }
        FlowLayout flowLayout = new FlowLayout(context);
        flowLayout.setId(2047279092);
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(-1, -2);
        layoutParams4.setMargins(eo.c(context, -4.0f), 0, 0, 0);
        flowLayout.setBackgroundColor(-1);
        if (z) {
            FrameLayout frameLayout = new FrameLayout(context);
            frameLayout.setId(2047279091);
            ViewGroup.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(-1, -2);
            frameLayout.setBackgroundColor(-1);
            frameLayout.setVisibility(8);
            linearLayout.addView(frameLayout, layoutParams5);
        }
        linearLayout.addView(flowLayout, layoutParams4);
        return linearLayout;
    }

    public static View c(Context context) {
        TTDislikeCommentLayout tTDislikeCommentLayout = new TTDislikeCommentLayout(context);
        tTDislikeCommentLayout.setId(2047279090);
        tTDislikeCommentLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
        tTDislikeCommentLayout.setOrientation(1);
        GradientDrawable gradientDrawable = new GradientDrawable();
        gradientDrawable.setShape(0);
        gradientDrawable.setColor(-1);
        gradientDrawable.setCornerRadius(eo.c(context, 8.0f));
        tTDislikeCommentLayout.setBackground(gradientDrawable);
        RelativeLayout relativeLayout = new RelativeLayout(context);
        relativeLayout.setId(2047279089);
        relativeLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, eo.c(context, 48.0f)));
        GradientDrawable gradientDrawable2 = new GradientDrawable();
        gradientDrawable2.setShape(0);
        gradientDrawable2.setColor(-1);
        gradientDrawable2.setCornerRadius(eo.c(context, 8.0f));
        relativeLayout.setBackground(gradientDrawable2);
        ImageView imageView = new ImageView(context);
        imageView.setId(2047279088);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-2, -2);
        imageView.setLayoutParams(layoutParams);
        layoutParams.addRule(15);
        layoutParams.setMarginStart(eo.c(context, 12.0f));
        imageView.setClickable(true);
        imageView.setFocusable(true);
        int color = Color.parseColor("#484848");
        ve veVar = new ve(48);
        veVar.c(color);
        float fC = eo.c(context, 2.0f);
        veVar.c(fC);
        int color2 = Color.parseColor("#666666");
        ve veVar2 = new ve(48);
        veVar2.c(color2);
        veVar2.c(fC);
        StateListDrawable stateListDrawable = new StateListDrawable();
        stateListDrawable.addState(new int[]{R.attr.state_pressed}, veVar);
        stateListDrawable.addState(new int[0], veVar2);
        imageView.setImageDrawable(stateListDrawable);
        relativeLayout.addView(imageView);
        TextView textView = new TextView(context);
        textView.setId(2047279087);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams2.addRule(15);
        textView.setLayoutParams(layoutParams2);
        textView.setEllipsize(TextUtils.TruncateAt.MARQUEE);
        textView.setGravity(17);
        textView.setSingleLine(true);
        textView.setText("其他建议");
        textView.setTextColor(Color.parseColor("#161823"));
        textView.setTextSize(2, 15.0f);
        textView.setTypeface(Typeface.DEFAULT);
        relativeLayout.addView(textView);
        TextView textView2 = new TextView(context);
        textView2.setId(2047279086);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(15);
        layoutParams3.addRule(21);
        layoutParams3.addRule(11);
        layoutParams3.setMarginStart(eo.c(context, 5.0f));
        layoutParams3.setMarginEnd(eo.c(context, 12.0f));
        textView2.setLayoutParams(layoutParams3);
        textView2.setTextSize(2, 14.0f);
        textView2.setTextColor(context.getResources().getColor(R.color.secondary_text_light_nodisable));
        textView2.setClickable(false);
        textView2.setGravity(5);
        textView2.setSingleLine(true);
        textView2.setText("提交");
        relativeLayout.addView(textView2);
        tTDislikeCommentLayout.addView(relativeLayout);
        View view = new View(context);
        view.setLayoutParams(new ViewGroup.LayoutParams(-1, eo.c(context, 0.5f)));
        view.setBackgroundColor(Color.parseColor("#0F161823"));
        tTDislikeCommentLayout.addView(view);
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
        linearLayout.setOrientation(0);
        EditText editText = new EditText(context);
        editText.setId(2047279085);
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(0, -2);
        layoutParams4.weight = 15.0f;
        layoutParams4.setMargins(eo.c(context, 12.0f), eo.c(context, 11.5f), 0, 0);
        editText.setLayoutParams(layoutParams4);
        editText.setLines(7);
        editText.setMaxLines(500);
        editText.setHint("请具体说明问题，我们将尽快处理");
        editText.setGravity(3);
        editText.setTextSize(2, 15.0f);
        editText.setHintTextColor(Color.parseColor("#57161823"));
        editText.setTextColor(Color.parseColor("#161823"));
        editText.setBackground(null);
        linearLayout.addView(editText);
        TextView textView3 = new TextView(context);
        textView3.setId(2047279084);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(0, -2);
        layoutParams5.weight = 1.0f;
        layoutParams5.setMargins(0, 0, eo.c(context, 12.0f), eo.c(context, 6.0f));
        layoutParams5.gravity = 8388693;
        textView3.setLayoutParams(layoutParams5);
        textView3.setText("0");
        textView3.setGravity(5);
        textView3.setHintTextColor(Color.parseColor("#57161823"));
        textView3.setTextColor(Color.parseColor("#BF161823"));
        textView3.setTextSize(2, 12.0f);
        linearLayout.addView(textView3);
        tTDislikeCommentLayout.addView(linearLayout);
        return tTDislikeCommentLayout;
    }
}
