package com.kwad.sdk.core.config;

import cn.com.chinatelecom.account.api.manager.SwitchNetManager;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.kwad.sdk.core.config.item.r;
import com.kwad.sdk.core.config.item.s;
import com.kwad.sdk.core.config.item.t;
import com.kwad.sdk.core.imageloader.KSImageLoader;
import java.util.ArrayList;

/* JADX INFO: loaded from: classes3.dex */
public final class c {
    public static final com.kwad.sdk.core.config.item.d aMY = new com.kwad.sdk.core.config.item.d("tkRenderTypeSwitch", false);
    public static final p aMZ = new p("feedTKIdleTime", 0L);
    public static l aNa = new l("batchReportCatchLimit", 20);
    public static l aNb = new l("exceptionCollectorSwitch", 1);
    public static l aNc = new l("catchExceptionReportSwitch", 1);
    public static l aNd = new l("mediaPlayerLogReport", 0);
    public static l aNe = new l("didCopySwitch", 1);
    public static l aNf = new l("enableHodor", 0);
    public static l aNg = new l("speedLimitSwitch", 1);
    public static l aNh = new l("speedLimitThreshold", 200);
    public static l aNi = new l("ksNativeAdCustomSwitch", 0);
    public static l aNj = new l("compoAndSoThreadPoolCoreSize", 0);
    public static l aNk = new l("forceActivateAfterInstalled", 0);
    public static l aNl = new l("spliceVideoInteractionType", 0);
    public static l aNm = new l("feedLoadOptimizeType", 0);
    public static l aNn = new l("feedLoadOptimizeExternalEnable", 0);
    public static l aNo = new l("nativeAdSlideClickDisable", 0);
    public static s aNp = new s("uaid", "");
    public static p aNq = new p("uaidExpireSec", 0L);
    public static p aNr = new p("uaidRequestDelayTime", 5L);
    public static l aNs = new l("interstitialAdLoadProcessChange", 0);
    public static l aNt = new l("interstitialAdActivityOpt", 0);
    public static l aNu = new l("formAdExitInterceptSwitch", 0);
    public static l aNv = new l("adLeaveConfirmSwitch", 0);
    public static l aNw = new l("viewLandingPageTaskDuration", 15);
    public static l aNx = new l("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d aNy = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static p aNz = new p("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d aNA = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d aNB = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d aNC = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static l aND = new l("commercialLoggerSwitch", 1);
    public static s aNE = new s("tkSoUrlV7a", "");
    public static s aNF = new s("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d aNG = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static n aNH = new n("playerConfig", null);
    public static t aNI = new t("pkgNameList", new ArrayList(0));
    public static t aNJ = new t("hostList", new ArrayList(0));
    public static t aNK = new t("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem aNL = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c aNM = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem aNN = new InstallActivateReminderConfigItem();
    public static f aNO = new f();
    public static com.kwad.sdk.core.config.item.e aNP = new com.kwad.sdk.core.config.item.e();
    public static m<Integer> aNQ = new m<>("adTKGrayConfig");
    public static q aNR = new q("realtimeReportActions", "");
    public static r aNS = new r();
    public static l aNT = new l("appInstallNoticeSecond", 0);
    public static l aNU = new l("installFloatingLayerPostion", 0);
    public static l aNV = new l("remindInstallStyle", 0);
    public static l aNW = new l("remindInstallTime", 60);
    public static l aNX = new l("watermarkKwaiIdSwitch", 0);
    public static l aNY = new l("insertScreenV2Switch", 0);
    public static l aNZ = new l("insertScreenAutoPlaySwitch", 0);
    public static k aOa = new k("insertScreenV2ShowConfig");
    public static l aOb = new l("environmentDetectEnable", 0);
    public static l aOc = new l("simCardInfoEnable", 0);
    public static l aOd = new l("baseStationEnable", 0);
    public static l aOe = new l("sensorEventEnable2", 0);
    public static l aOf = new l("lpAutoDownloadApkSwitch", 1);
    public static l aOg = new l("autoDownloadUrlSwitch", 0);
    public static l aOh = new l("insertScreenAdType", 0);
    public static l aOi = new l("interstitialAutoCallAppCountDaily", 1);
    public static l aOj = new l("mediaControlPlaySwitch", 1);
    public static s aOk = new s("appStatusSoUrlV7a", "");
    public static s aOl = new s("appStatusSoUrlV8a", "");
    public static s aOm = new s("appStatusSoVersion", "");
    public static l aOn = new l("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d aOo = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static i aOp = new i();
    public static com.kwad.sdk.core.config.item.d aOq = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d aOr = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static s aOs = new s("TKSwitchExtra", "");
    public static com.kwad.sdk.core.config.item.d aOt = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d aOu = new com.kwad.sdk.core.config.item.d("TKJsonSubThread", true);
    public static com.kwad.sdk.core.config.item.d aOv = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d aOw = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static l aOx = new l("forceActivate", 0);
    public static l aOy = new l("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d aOz = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static s aOA = new s("nativeAndAnrDynamic", "");
    public static l aOB = new l("kwaiAppVersionSwitch", 1);
    public static com.kwad.sdk.core.config.item.d aOC = new com.kwad.sdk.core.config.item.d("disableLogcatOAID", false);
    public static s aOD = new s("userAgent");
    public static l aOE = new l("biddingLogSwitch", 0);
    public static l aOF = new l("forceActiveThreshold", 5);
    public static l aOG = new l("forceActiveInterval", 3);
    public static l aOH = new l("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d aOI = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static h aOJ = new h("adExposureAreaPercent", 0.3f);
    public static h aOK = new h("adExposureTime", -1.0f);
    public static h aOL = new h("drawAdExposureAreaPercent", 0.7f);
    public static h aOM = new h("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d aON = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d aOO = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static l aOP = new l("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d aOQ = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static com.kwad.sdk.core.config.item.d aOR = new com.kwad.sdk.core.config.item.d("forceGetAudioFocus", false);
    public static l aOS = new l("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d aOT = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d aOU = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static p aOV = new p("obiwanLogFilesDiskQuota", 52428800L);
    public static n aOW = new n("logCommandResult", "", false);
    public static p aOX = new p("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d aOY = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static l aOZ = new l("playableAutoPlayEnable", 1);
    public static l aPa = new l("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d aPb = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d aPc = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static l aPd = new l("weaponSwitch", 1);
    public static l aPe = new l("kvModeV2", 0);
    public static j aPf = new j();
    public static l aPg = new l("idcRollbackInterval", 0);
    public static p aPh = new p("currentServerTimeMs");
    public static l aPi = new l("clientProofreadTimeErrorRangeHours", 100);
    public static h aPj = new h("adTraceReportRate", 1.0f);
    public static l aPk = new l("adTraceRepeatEnable", 0);
    public static l aPl = new l("appHeartBeatInterval", 0);
    public static l aPm = new l("insertShowPercent", 100);
    public static l aPn = new l("adCacheCode", 0);
    public static s aPo = new s("installTipsContentDesc", "");
    public static s aPp = new s("installTipsPositiveActionDesc", "");
    public static s aPq = new s("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d aPr = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static com.kwad.sdk.core.config.item.d aPs = new com.kwad.sdk.core.config.item.d("resourceWarmupSwitch", false);
    public static l aPt = new l("resourceWarmupDelayTime", 5);
    public static s aPu = new s("perfMonitorV2", "");
    public static l aPv = new l("neoVideoAdaptStrategy", 1);
    public static l aPw = new l("feedTKLoadTimeOut", Integer.valueOf(SwitchNetManager.DELAY_CHECK));
    public static l aPx = new l("drawTKLoadTimeOut", 2000);
    public static l aPy = new l("nativeTKLoadTimeOut", 3000);
    public static com.kwad.sdk.core.config.item.d aPz = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static l aPA = new l("adImageLoaderCacheLimitSize", -1);
    public static com.kwad.sdk.core.config.item.d aPB = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static l aPC = new l("videoCacheOpt", 0);
    public static s aPD = new s("ranger", "");
    public static l aPE = new l("hdrConfig", 0);
    public static s aPF = new s("packageInstall", "");
    public static s aPG = new s("eplV1", "");
    public static s aPH = new s("threadPoolPerfMonitor", "");
    public static s aPI = new s("threadPoolParams", "");
    public static g aPJ = new g("crashUploadRate", Double.valueOf(1.0d));
    public static g aPK = new g("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d aPL = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d aPM = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d aPN = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d aPO = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d aPP = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d aPQ = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d aPR = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static l aPS = new l("tubeRenderType", 0);
    public static l aPT = new l("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d aPU = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static com.kwad.sdk.core.config.item.d aPV = new com.kwad.sdk.core.config.item.d("ecExtInfoSwitch", false);
    public static s aPW = new s("trackBlackUrlConfig", "");
    public static l aPX = new l("tkMemCacheSize", 0);
    public static t aPY = new t("preloadMemCacheTemplateIds", new ArrayList(0));
    public static l aPZ = new l("kGeoInfoConfig", 1);
    public static l aQa = new l("appMonitorSwitch", 0);
    public static l aQb = new l("videoCacheErrorCallbackSwitch", 0);
    public static l aQc = new l("tkErrorDetailCount", 1);
    public static l aQd = new l("videoLaunchOptimiseSwitch", 0);
    public static l aQe = new l("enableInitStartMode", 1);
    public static s aQf = new s("localLogConfig", "");
    public static s aQg = new s("adLogRetryConfig", "");
    public static o aQh = new o("dpSchemeFlags");
    public static com.kwad.sdk.core.config.item.d aQi = new com.kwad.sdk.core.config.item.d("feedAdBgTransparentSwitch");
    public static l aQj = new l("adRequestNum", 1);
    public static l aQk = new l("carouselInterval", Integer.valueOf(KSImageLoader.InnerImageLoadingListener.MAX_DURATION));
    public static p aQl = new p("packageInfoLimiter", 0L);
    public static com.kwad.sdk.core.config.item.d aQm = new com.kwad.sdk.core.config.item.d("showOptimizedProgress");
    public static l aQn = new l("optimizeProgressMethod", 0);
    public static l aQo = new l("splashLoadTimeOptimize", 0);
    public static p aQp = new p("splashVisibleCheckDelayTime", 500L);
    public static com.kwad.sdk.core.config.item.d aQq = new com.kwad.sdk.core.config.item.d("isWaynePlayerValid", false);
    public static com.kwad.sdk.core.config.item.d aQr = new com.kwad.sdk.core.config.item.d("isWaynePlayerAsDefaultPlayer", false);
    public static n aQs = new n("waynePlayerPlayConfig", null);
    public static l aQt = new l("waynePlayerSupportAndroidApi", 24);
    public static com.kwad.sdk.core.config.item.d aQu = new com.kwad.sdk.core.config.item.d("apkBroadcastReceiverSwitch", true);
    public static com.kwad.sdk.core.config.item.d aQv = new com.kwad.sdk.core.config.item.d("closureSwitch", false);
    public static com.kwad.sdk.core.config.item.d aQw = new com.kwad.sdk.core.config.item.d("closureVideoTwoSwitch", false);
    public static s aQx = new s("closureH5AuthUrl", "");
    public static s aQy = new s("closureH5AuthAppId", "");
    public static s aQz = new s("closureH5AuthPathPart", "");
    public static s aQA = new s("closureSupportSdkVersion", "4.8.30");
    public static s aQB = new s("openAppId", "");
    public static com.kwad.sdk.core.config.item.d aQC = new com.kwad.sdk.core.config.item.d("enableThreadOpt2", false);
    public static n aQD = new n("cheatInfoConfig", null);
    public static n aQE = new n("featureCollectConfig", null);
    public static final l aQF = new l("installerCheckPkgAbSwitch", 0);
    public static final s aQG = new s("installerCheckExtraPkgs", "");
    public static final l aQH = new l("probeBatch", 0);
    public static s aQI = new s("thKwaiMarketUrl", "");
    public static l aQJ = new l("maxKCLogReporterCacheSize", 512);
    public static l aQK = new l("diskMonitorEnable", 0);
    public static n aQL = new n("androidTargetDiskPathList", null);
    public static s aQM = new s("chinaMobileAndroidPublicKey", "");
    public static t aQN = new t("chinaMobileHostBlackList", new ArrayList());
    public static s aQO = new s("ksadCMTokenPublicKey", "");
    public static com.kwad.sdk.core.config.item.d aQP = new com.kwad.sdk.core.config.item.d("interAggregateTKRenderSwitch", false);
    public static com.kwad.sdk.core.config.item.d aQQ = new com.kwad.sdk.core.config.item.d("enablePluginInflaterFix", false);

    public static void init() {
    }
}
