package com.byazt.xc;

import android.content.Context;
import android.graphics.Color;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.byazt.ga.LottieAnimationView;
import com.byazt.nr.eo;
import com.byazt.nr.z;
import com.byazt.oq.FlowLightView;
import com.byazt.or.i;
import com.bykv.vk.component.ttvideo.player.MediaPlayer;

/* JADX INFO: loaded from: classes2.dex */
@com.byazt.zqa.c(c = {0, 1, 674, 13})
public class tt {
    public static View c(Context context) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
        linearLayout.setGravity(81);
        LinearLayout linearLayout2 = new LinearLayout(context);
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(eo.c(context, 46.0f), eo.c(context, 32.0f)));
        linearLayout2.setBackground(i.c(0, Integer.valueOf(Color.parseColor("#99000000")), new int[]{eo.c(context, 40.0f)}, null, Integer.valueOf(eo.c(context, 1.0f)), Integer.valueOf(Color.parseColor("#88FFFFFF"))));
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        ImageView imageView = new ImageView(context);
        imageView.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        z.c(context, "tt_splash_slide_up_10", (View) imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        linearLayout2.addView(imageView);
        linearLayout.addView(linearLayout2);
        return linearLayout;
    }

    public static View tt(Context context) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
        linearLayout.setGravity(81);
        LinearLayout linearLayout2 = new LinearLayout(context);
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(-1, eo.c(context, 100.0f)));
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        FrameLayout frameLayout = new FrameLayout(context);
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(-1, -2));
        ImageView imageView = new ImageView(context);
        imageView.setId(2097610751);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(eo.c(context, 19.0f), eo.c(context, 15.0f));
        layoutParams.gravity = 1;
        imageView.setLayoutParams(layoutParams);
        imageView.setScaleType(ImageView.ScaleType.FIT_XY);
        z.c(context, "tt_white_slide_up", imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        ImageView imageView2 = new ImageView(context);
        imageView2.setId(2097610750);
        FrameLayout.LayoutParams layoutParams2 = new FrameLayout.LayoutParams(eo.c(context, 19.0f), eo.c(context, 15.0f));
        layoutParams2.gravity = 1;
        layoutParams2.topMargin = eo.c(context, 7.0f);
        imageView2.setLayoutParams(layoutParams2);
        imageView2.setScaleType(ImageView.ScaleType.FIT_XY);
        z.c(context, "tt_white_slide_up", imageView2, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        ImageView imageView3 = new ImageView(context);
        imageView3.setId(2097610749);
        FrameLayout.LayoutParams layoutParams3 = new FrameLayout.LayoutParams(eo.c(context, 19.0f), eo.c(context, 15.0f));
        layoutParams3.gravity = 1;
        layoutParams3.topMargin = eo.c(context, 14.0f);
        imageView3.setLayoutParams(layoutParams3);
        imageView3.setScaleType(ImageView.ScaleType.FIT_XY);
        z.c(context, "tt_white_slide_up", imageView3, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        frameLayout.addView(imageView);
        frameLayout.addView(imageView2);
        frameLayout.addView(imageView3);
        linearLayout2.addView(frameLayout);
        View view = new View(context);
        view.setLayoutParams(new LinearLayout.LayoutParams(-1, 0, 1.0f));
        linearLayout2.addView(view);
        TextView textView = new TextView(context);
        textView.setId(2097610748);
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(-1, -2);
        layoutParams4.setMargins(0, 0, 0, eo.c(context, 5.0f));
        textView.setLayoutParams(layoutParams4);
        textView.setGravity(1);
        textView.setTextColor(-1);
        textView.setTextSize(1, 14.0f);
        linearLayout2.addView(textView);
        linearLayout.addView(linearLayout2);
        return linearLayout;
    }

    public static View ve(Context context) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        z.c(context, "tt_splash_unlock_btn_bg", linearLayout, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        linearLayout.setPadding(eo.c(context, 38.0f), eo.c(context, 20.0f), eo.c(context, 38.0f), eo.c(context, 20.0f));
        linearLayout.setGravity(17);
        linearLayout.setOrientation(0);
        ImageView imageView = new ImageView(context);
        imageView.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        z.c(context, "tt_splash_shake_hand", (View) imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        TextView textView = new TextView(context);
        textView.setId(2097610747);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(-2, -2);
        layoutParams.setMargins(eo.c(context, 8.0f), 0, 0, 0);
        textView.setLayoutParams(layoutParams);
        textView.setTextSize(2, 17.0f);
        textView.setTextColor(-1);
        linearLayout.addView(imageView);
        linearLayout.addView(textView);
        return linearLayout;
    }

    public static View uj(Context context) {
        RelativeLayout relativeLayout = new RelativeLayout(context);
        relativeLayout.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        RelativeLayout relativeLayout2 = new RelativeLayout(context);
        relativeLayout2.setId(2097610746);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(eo.c(context, 247.0f), eo.c(context, 56.0f));
        layoutParams.addRule(14);
        relativeLayout2.setLayoutParams(layoutParams);
        z.c(context, "tt_splash_unlock_btn_bg", relativeLayout2, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        ImageView imageView = new ImageView(context);
        imageView.setId(2097610745);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(eo.c(context, 48.0f), eo.c(context, 48.0f));
        layoutParams2.addRule(20);
        layoutParams2.addRule(15);
        layoutParams2.setMargins(eo.c(context, 4.0f), 0, 0, 0);
        imageView.setLayoutParams(layoutParams2);
        z.c(context, "tt_splash_unlock_image_go", imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        FlowLightView flowLightView = new FlowLightView(context);
        flowLightView.setId(2097610744);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-1, eo.c(context, 24.0f));
        layoutParams3.addRule(15);
        layoutParams3.setMargins(eo.c(context, 12.0f), 0, eo.c(context, 12.0f), 0);
        layoutParams3.addRule(16, 2097610743);
        layoutParams3.addRule(17, 2097610745);
        flowLightView.setLayoutParams(layoutParams3);
        ImageView imageView2 = new ImageView(context);
        imageView2.setId(2097610743);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(eo.c(context, 48.0f), eo.c(context, 48.0f));
        layoutParams4.addRule(21);
        layoutParams4.addRule(15);
        layoutParams4.setMarginStart(eo.c(context, 2.0f));
        layoutParams4.setMarginEnd(eo.c(context, 4.0f));
        imageView2.setLayoutParams(layoutParams4);
        z.c(context, "tt_splash_unlock_icon_empty", imageView2, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        relativeLayout2.addView(imageView);
        relativeLayout2.addView(flowLightView);
        relativeLayout2.addView(imageView2);
        TextView textView = new TextView(context);
        textView.setId(2097610742);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams5.addRule(3, 2097610746);
        layoutParams5.addRule(14);
        layoutParams5.setMargins(0, eo.c(context, 12.0f), 0, 0);
        textView.setLayoutParams(layoutParams5);
        textView.setTextColor(-1);
        textView.setShadowLayer(eo.c(context, 3.0f), eo.c(context, 3.0f), eo.c(context, 3.0f), Color.parseColor("#99000000"));
        relativeLayout.addView(relativeLayout2);
        relativeLayout.addView(textView);
        return relativeLayout;
    }

    public static View n(Context context) {
        RelativeLayout relativeLayout = new RelativeLayout(context);
        relativeLayout.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        relativeLayout.setGravity(16);
        relativeLayout.setClipChildren(false);
        ImageView imageView = new ImageView(context);
        imageView.setId(2097610735);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(eo.c(context, 36.0f), eo.c(context, 36.0f));
        layoutParams.addRule(14);
        layoutParams.addRule(8, 2097610732);
        layoutParams.setMargins(0, 0, 0, eo.c(context, -24.0f));
        imageView.setLayoutParams(layoutParams);
        z.c(context, "tt_splash_slide_up_circle", (View) imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        imageView.setAlpha(0.0f);
        ImageView imageView2 = new ImageView(context);
        imageView2.setId(2097610734);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(eo.c(context, 67.0f), eo.c(context, 51.0f));
        layoutParams2.addRule(14);
        layoutParams2.addRule(1, 2097610732);
        layoutParams2.addRule(8, 2097610732);
        layoutParams2.setMargins(eo.c(context, -7.0f), 0, 0, eo.c(context, -20.0f));
        imageView2.setLayoutParams(layoutParams2);
        z.c(context, "tt_splash_slide_up_finger", (View) imageView2, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        imageView2.setAlpha(0.0f);
        ImageView imageView3 = new ImageView(context);
        imageView3.setId(2097610733);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(eo.c(context, 10.0f), 0);
        layoutParams3.addRule(14);
        layoutParams3.addRule(8, 2097610732);
        imageView3.setLayoutParams(layoutParams3);
        z.c(context, "tt_splash_slide_up_bg", (View) imageView3, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        ImageView imageView4 = new ImageView(context);
        imageView4.setId(2097610732);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(eo.c(context, 14.0f), eo.c(context, 100.0f));
        layoutParams4.addRule(14);
        imageView4.setLayoutParams(layoutParams4);
        z.c(context, "tt_splash_slide_up_arrow", (View) imageView4, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        TextView textView = new TextView(context);
        textView.setId(2097610731);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(3, 2097610732);
        textView.setLayoutParams(layoutParams5);
        textView.setTextColor(-1);
        textView.setText("向上滑动");
        textView.setTextSize(2, 18.0f);
        textView.setShadowLayer(eo.c(context, 4.0f), eo.c(context, 3.0f), eo.c(context, 3.0f), Color.parseColor("#99000000"));
        textView.setGravity(1);
        TextView textView2 = new TextView(context);
        textView2.setId(2097610730);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(3, 2097610731);
        textView2.setLayoutParams(layoutParams6);
        textView2.setTextColor(-1);
        textView2.setTextSize(2, 14.0f);
        textView2.setShadowLayer(eo.c(context, 4.0f), eo.c(context, 3.0f), eo.c(context, 3.0f), Color.parseColor("#99000000"));
        textView2.setGravity(1);
        relativeLayout.addView(imageView);
        relativeLayout.addView(imageView2);
        relativeLayout.addView(imageView3);
        relativeLayout.addView(imageView4);
        relativeLayout.addView(textView);
        relativeLayout.addView(textView2);
        return relativeLayout;
    }

    public static View a(Context context) {
        RelativeLayout relativeLayout = new RelativeLayout(context);
        relativeLayout.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        relativeLayout.setClipChildren(false);
        relativeLayout.setClipToPadding(false);
        relativeLayout.setGravity(16);
        RelativeLayout relativeLayout2 = new RelativeLayout(context);
        relativeLayout2.setId(2097610729);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams.addRule(13);
        layoutParams.setMargins(0, 0, 0, 0);
        relativeLayout2.setLayoutParams(layoutParams);
        relativeLayout2.setClipChildren(false);
        relativeLayout2.setClipToPadding(false);
        relativeLayout2.setPadding(eo.c(context, 60.0f), 0, 0, 0);
        relativeLayout.addView(relativeLayout2);
        ImageView imageView = new ImageView(context);
        imageView.setId(2097610735);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(eo.c(context, 80.0f), eo.c(context, 80.0f));
        layoutParams2.addRule(9);
        layoutParams2.addRule(12);
        layoutParams2.setMargins(0, 0, 0, -eo.c(context, 40.0f));
        imageView.setLayoutParams(layoutParams2);
        imageView.setAlpha(0);
        z.c(context, "tt_splash_slide_up_circle", (View) imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        relativeLayout2.addView(imageView);
        ImageView imageView2 = new ImageView(context);
        imageView2.setId(2097610733);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(eo.c(context, 16.0f), 0);
        layoutParams3.addRule(9);
        layoutParams3.addRule(12);
        layoutParams3.setMargins(eo.c(context, 36.0f), 0, 0, 0);
        imageView2.setLayoutParams(layoutParams3);
        z.c(context, "tt_splash_slide_up_bg", (View) imageView2, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        relativeLayout2.addView(imageView2);
        ImageView imageView3 = new ImageView(context);
        imageView3.setId(2097610734);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(eo.c(context, 160.0f), eo.c(context, 120.0f));
        layoutParams4.addRule(12);
        layoutParams4.setMargins(eo.c(context, 35.0f), 0, 0, -eo.c(context, 40.0f));
        imageView3.setLayoutParams(layoutParams4);
        imageView3.setAlpha(0);
        z.c(context, "tt_splash_slide_up_finger", (View) imageView3, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        relativeLayout2.addView(imageView3);
        TextView textView = new TextView(context);
        textView.setId(2097610730);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, eo.c(context, 20.0f));
        layoutParams5.addRule(12);
        layoutParams5.setMargins(0, 0, 0, -eo.c(context, 95.0f));
        textView.setLayoutParams(layoutParams5);
        textView.setGravity(1);
        textView.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView.setTextColor(-1);
        textView.setTextSize(1, 14.0f);
        relativeLayout.addView(textView);
        return relativeLayout;
    }

    public static View sp(Context context) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        linearLayout.setOrientation(1);
        TextView textView = new TextView(context);
        textView.setId(2097610728);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(-2, -2);
        layoutParams.gravity = 17;
        layoutParams.setMargins(0, eo.c(context, 12.0f), 0, 0);
        textView.setLayoutParams(layoutParams);
        textView.setVisibility(4);
        linearLayout.addView(textView);
        LinearLayout linearLayout2 = new LinearLayout(context);
        linearLayout2.setId(2097610727);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(eo.c(context, 110.0f), eo.c(context, 110.0f));
        layoutParams2.gravity = 17;
        linearLayout2.setLayoutParams(layoutParams2);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        linearLayout.addView(linearLayout2);
        TextView textView2 = new TextView(context);
        textView2.setId(2097610726);
        textView2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        textView2.setVisibility(4);
        textView2.setTextSize(2, 14.0f);
        linearLayout2.addView(textView2);
        ImageView imageView = new ImageView(context);
        imageView.setId(2097610725);
        imageView.setLayoutParams(new LinearLayout.LayoutParams(eo.c(context, 60.0f), eo.c(context, 60.0f)));
        z.c(context, "tt_splash_rock", imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        linearLayout2.addView(imageView);
        TextView textView3 = new TextView(context);
        textView3.setId(2097610724);
        textView3.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        textView3.setSingleLine(true);
        textView3.setText("摇一摇");
        textView3.setTextColor(-1);
        textView3.setTextSize(2, 14.0f);
        linearLayout2.addView(textView3);
        TextView textView4 = new TextView(context);
        textView4.setId(2097610723);
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 17;
        layoutParams3.setMargins(0, eo.c(context, 12.0f), 0, 0);
        textView4.setLayoutParams(layoutParams3);
        textView4.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView4.setText("前往详情页或第三方应用");
        textView4.setTextColor(-1);
        linearLayout.addView(textView4);
        return linearLayout;
    }

    public static View x(Context context) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        linearLayout.setOrientation(1);
        TextView textView = new TextView(context);
        textView.setId(2097610726);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(-2, -2);
        layoutParams.gravity = 17;
        layoutParams.setMargins(0, eo.c(context, 12.0f), 0, 0);
        textView.setLayoutParams(layoutParams);
        textView.setVisibility(4);
        textView.setTextSize(1, 18.0f);
        linearLayout.addView(textView);
        TextView textView2 = new TextView(context);
        textView2.setId(2097610728);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams2.gravity = 17;
        textView2.setLayoutParams(layoutParams2);
        textView2.setVisibility(4);
        textView2.setTextSize(1, 14.0f);
        linearLayout.addView(textView2);
        LinearLayout linearLayout2 = new LinearLayout(context);
        linearLayout2.setId(2097610727);
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 17;
        linearLayout2.setLayoutParams(layoutParams3);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        linearLayout.addView(linearLayout2);
        ImageView imageView = new ImageView(context);
        imageView.setId(2097610725);
        imageView.setLayoutParams(new LinearLayout.LayoutParams(eo.c(context, 60.0f), eo.c(context, 60.0f)));
        z.c(context, "tt_splash_rock", imageView, MediaPlayer.MEDIA_PLAYER_OPTION_LAST_VIDEO_RENDER_TIME);
        linearLayout2.addView(imageView);
        TextView textView3 = new TextView(context);
        textView3.setId(2097610724);
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams4.gravity = 17;
        layoutParams4.setMargins(0, eo.c(context, 12.0f), 0, 0);
        textView3.setLayoutParams(layoutParams4);
        textView3.setSingleLine(true);
        textView3.setText("摇一摇 或 点击图标");
        textView3.setTextColor(-1);
        textView3.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView3.setTextSize(1, 18.0f);
        linearLayout.addView(textView3);
        TextView textView4 = new TextView(context);
        textView4.setId(2097610723);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams5.gravity = 17;
        layoutParams5.setMargins(0, eo.c(context, 12.0f), 0, 0);
        textView4.setLayoutParams(layoutParams5);
        textView4.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView4.setTextSize(1, 14.0f);
        textView4.setText("前往详情页或第三方应用");
        textView4.setTextColor(-1);
        linearLayout.addView(textView4);
        return linearLayout;
    }

    public static View i(Context context) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        linearLayout.setOrientation(1);
        LinearLayout linearLayout2 = new LinearLayout(context);
        linearLayout2.setId(2097610722);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(eo.c(context, 110.0f), eo.c(context, 110.0f));
        layoutParams.gravity = 17;
        layoutParams.setMargins(0, 0, 0, eo.c(context, 4.0f));
        linearLayout2.setLayoutParams(layoutParams);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        linearLayout2.setVisibility(0);
        linearLayout.addView(linearLayout2);
        LottieAnimationView lottieAnimationView = new LottieAnimationView(context);
        lottieAnimationView.setId(2097610706);
        lottieAnimationView.setLayoutParams(new LinearLayout.LayoutParams(eo.c(context, 100.0f), eo.c(context, 100.0f)));
        linearLayout2.addView(lottieAnimationView);
        TextView textView = new TextView(context);
        textView.setId(2097610719);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams2.gravity = 17;
        textView.setLayoutParams(layoutParams2);
        textView.setSingleLine(true);
        textView.setText("扭动手机");
        textView.setTextColor(-1);
        textView.setTextSize(1, 18.0f);
        textView.setTypeface(null, 1);
        textView.setShadowLayer(2.0f, 0.0f, 0.5f, Color.parseColor("#4D000000"));
        linearLayout.addView(textView);
        TextView textView2 = new TextView(context);
        textView2.setId(2097610718);
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 17;
        textView2.setLayoutParams(layoutParams3);
        textView2.setSingleLine(true);
        textView2.setText("前往详情页或第三方应用");
        textView2.setTextColor(-1);
        textView2.setTextSize(1, 14.0f);
        textView2.setTypeface(null, 1);
        textView2.setShadowLayer(2.0f, 0.0f, 0.5f, Color.parseColor("#4D000000"));
        linearLayout.addView(textView2);
        return linearLayout;
    }
}
