package com.kwad.sdk.core.b.a;

import com.kwad.components.core.innerEc.InnerEcUserLoginBindInfo;
import com.kwad.components.core.innerEc.logger.BaseInnerEcMsg;
import com.kwad.components.core.innerEc.logger.InnerEcError;
import com.kwad.components.core.innerEc.logger.InnerEcEvent;
import com.kwad.components.core.innerEc.qcpx.ReceiveQcpxBody;
import com.kwad.components.core.pfmonitor.model.DiskReportInfo;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.sdk.kgeo.KGeoInfo;
import com.kwad.sdk.mobileid.UaidInfo;
import com.kwad.sdk.monitor.MediaMessageInfo;
import com.kwad.sdk.resourceCache.model.WarmUpReportMessage;

/* JADX INFO: loaded from: classes3.dex */
public final class df {
    public static void Md() {
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.i.class, new of());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.e.class, new ch());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.s.class, new ln());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.a.class, new o());
        hh.Me().put(com.kwad.components.core.innerEc.live.base.c.class, new lc());
        hh.Me().put(com.kwad.components.core.pfmonitor.model.f.class, new kn());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.i.class, new ew());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.n.class, new iu());
        hh.Me().put(com.kwad.components.core.video.a.d.b.class, new nu());
        hh.Me().put(com.kwad.components.core.innerEc.live.a.o.a.class, new hp());
        hh.Me().put(com.kwad.components.core.webview.jshandler.j.b.class, new fr());
        hh.Me().put(com.kwad.components.core.webview.jshandler.i.a.class, new fp());
        hh.Me().put(com.kwad.components.core.webview.jshandler.bf.a.class, new mz());
        hh.Me().put(com.kwad.components.core.pfmonitor.model.a.class, new dw());
        hh.Me().put(ReceiveQcpxBody.class, new kk());
        hh.Me().put(com.kwad.components.core.webview.jshandler.at.a.class, new bi());
        hh.Me().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new hk());
        hh.Me().put(com.kwad.components.core.webview.jshandler.aj.a.class, new no());
        hh.Me().put(com.kwad.components.core.webview.jshandler.as.a.class, new jt());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.u.class, new lr());
        hh.Me().put(com.kwad.components.core.m.a.class, new v());
        hh.Me().put(com.kwad.components.core.innerEc.live.a.d.a.class, new hv());
        hh.Me().put(com.kwad.components.core.webview.jshandler.m.a.class, new gq());
        hh.Me().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new af());
        hh.Me().put(com.kwad.components.core.innerEc.followuser.a.class, new fa());
        hh.Me().put(com.kwad.components.core.pfmonitor.model.b.class, new dy());
        hh.Me().put(MediaMessageInfo.class, new io());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ap.b.class, new hd());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.g.class, new cs());
        hh.Me().put(com.kwad.components.core.webview.jshandler.u.a.class, new mq());
        hh.Me().put(KGeoInfo.class, new hi());
        hh.Me().put(com.kwad.components.core.webview.jshandler.g.a.class, new fn());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.w.class, new nn());
        hh.Me().put(com.kwad.sdk.monitor.b.C0534b.class, new lh());
        hh.Me().put(com.kwad.components.core.webview.jshandler.f.a.class, new fm());
        hh.Me().put(com.kwad.components.core.offline.moitor.d.class, new nm());
        hh.Me().put(DiskReportInfo.class, new dx());
        hh.Me().put(com.kwad.components.core.webview.jshandler.a.f.a.class, new co());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.k.class, new he());
        hh.Me().put(BaseInnerEcMsg.class, new bz());
        hh.Me().put(com.kwad.components.core.webview.jshandler.e.b.class, new gf());
        hh.Me().put(WarmUpReportMessage.class, new ob());
        hh.Me().put(com.kwad.components.core.webview.jshandler.bj.a.class, new hg());
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.e.class, new hy());
        hh.Me().put(com.kwad.components.core.innerEc.live.f.a.class, new lp());
        hh.Me().put(com.kwad.components.core.webview.a.c.class, new jn());
        hh.Me().put(com.kwad.components.core.webview.jshandler.av.a.class, new bu());
        hh.Me().put(com.kwad.components.core.webview.jshandler.be.a.class, new oa());
        hh.Me().put(com.kwad.components.core.webview.jshandler.m.b.class, new gr());
        hh.Me().put(com.kwad.components.core.webview.jshandler.l.a.class, new fs());
        hh.Me().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new ae());
        hh.Me().put(com.kwad.components.core.webview.jsPublicBridge.a.a.C0463a.class, new hj());
        hh.Me().put(com.kwad.components.core.video.a.d.a.class, new nt());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.t.class, new lo());
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.c.class, new hs());
        hh.Me().put(com.kwad.components.core.video.a.e.class, new oc());
        hh.Me().put(com.kwad.components.core.b.b.class, new hn());
        hh.Me().put(com.kwad.components.core.webview.jshandler.a.c.class, new jd());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ay.a.class, new od());
        hh.Me().put(com.kwad.components.core.innerEc.live.base.b.class, new hx());
        hh.Me().put(com.kwad.components.core.webview.jshandler.au.b.class, new bm());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.b.class, new bn());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.c.class, new br());
        hh.Me().put(com.kwad.components.core.webview.jshandler.a.e.a.class, new li());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.h.class, new dp());
        hh.Me().put(com.kwad.components.core.innerEc.live.base.d.class, new ld());
        hh.Me().put(UaidInfo.class, new nj());
        hh.Me().put(InnerEcUserLoginBindInfo.class, new gn());
        hh.Me().put(com.kwad.sdk.monitor.b.a.class, new lg());
        hh.Me().put(com.kwad.components.core.innerEc.live.a.m.a.class, new dz());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ah.a.class, new kd());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.j.class, new ft());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.b.x.a.class, new bp());
        hh.Me().put(com.kwad.components.core.innerEc.live.a.a.C0435a.class, new iq());
        hh.Me().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new ad());
        hh.Me().put(com.kwad.components.core.webview.jshandler.v.b.class, new mm());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.f.class, new cp());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ap.a.class, new hc());
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.d.class, new ht());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ag.a.class, new kc());
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.g.class, new ic());
        hh.Me().put(com.kwad.components.core.webview.jshandler.bg.a.class, new ga());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.b.u.b.class, new mg());
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.b.class, new hl());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ao.b.class, new fv());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.b.h.b.class, new kb());
        hh.Me().put(InnerEcEvent.class, new gl());
        hh.Me().put(com.kwad.components.core.webview.a.a.b.class, new ed());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.x.class, new nr());
        hh.Me().put(MediaMessageInfo.MediaPermissionInfo.class, new ip());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.v.class, new mf());
        hh.Me().put(com.kwad.components.core.webview.jshandler.a.a.C0465a.class, new cj());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.q.class, new jz());
        hh.Me().put(com.kwad.components.core.webview.a.b.class, new jl());
        hh.Me().put(com.kwad.components.core.webview.a.a.C0461a.class, new ea());
        hh.Me().put(com.kwad.components.core.webview.jshandler.a.C0464a.class, new an());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.d.class, new bt());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.m.class, new hr());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.p.class, new jr());
        hh.Me().put(com.kwad.components.core.webview.jshandler.au.a.class, new bl());
        hh.Me().put(com.kwad.components.core.webview.jshandler.j.a.class, new fq());
        hh.Me().put(com.kwad.sdk.a.a.a.a.class, new gs());
        hh.Me().put(com.kwad.components.core.innerEc.live.f.b.class, new lq());
        hh.Me().put(com.kwad.components.core.innerEc.live.base.e.class, new le());
        hh.Me().put(InnerEcError.class, new gk());
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.f.class, new hz());
        hh.Me().put(com.kwad.components.core.offline.moitor.b.class, new jk());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.r.class, new ll());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.o.class, new jm());
        hh.Me().put(com.kwad.components.core.innerEc.followuser.b.class, new fb());
        hh.Me().put(com.kwad.components.core.webview.jshandler.h.a.class, new fo());
        hh.Me().put(com.kwad.components.core.page.c.a.class, new hq());
        hh.Me().put(com.kwad.components.core.webview.jshandler.q.a.class, new is());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.z.class, new nz());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ak.a.class, new gc());
        hh.Me().put(com.kwad.components.core.webview.jshandler.y.a.class, new x());
        hh.Me().put(WebCardVideoPositionHandler.VideoPosition.class, new ny());
        hh.Me().put(com.kwad.components.core.webview.jshandler.ba.a.class, new id());
        hh.Me().put(com.kwad.components.core.webview.jshandler.an.a.class, new di());
        hh.Me().put(com.kwad.components.core.innerEc.live.config.net.a.class, new ep());
        hh.Me().put(com.kwad.components.core.webview.tachikoma.c.y.class, new nv());
    }
}
