package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.convert.AdLinkMonitorMsg;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdCouponReceiveParam;
import com.kwad.sdk.core.response.model.AdGlobalConfigInfo;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.AdVideoPreCacheConfig;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.LiveDetailReward;
import com.kwad.sdk.core.response.model.LiveInfo;
import com.kwad.sdk.core.response.model.LiveRewardInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.internal.api.AdLabelImpl;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.internal.api.SplashExtraDataImpl;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes3.dex */
public final class hh {
    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aSG;

    static {
        HashMap map = new HashMap();
        aSG = map;
        map.put(AdInfo.ComplianceInfo.class, new ct());
        aSG.put(AdStyleInfo.AdBrowseInfo.class, new l());
        aSG.put(com.kwad.sdk.core.request.model.d.class, new jh());
        aSG.put(WebCloseStatus.class, new oe());
        aSG.put(AdInfo.AdLiveTypeInfo.class, new ag());
        aSG.put(com.kwad.sdk.core.request.model.g.class, new nq());
        aSG.put(AdMatrixInfo.SplashActionBarInfo.class, new lx());
        aSG.put(AdInfo.AdFeedInfo.class, new u());
        aSG.put(AdMatrixInfo.BaseMatrixTemplate.class, new cb());
        aSG.put(StatusInfo.SplashStyleControl.class, new mj());
        aSG.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new jw());
        aSG.put(AdStyleInfo.ExposeTagInfo.class, new eo());
        aSG.put(AdInfo.AdStyleConfInfo.class, new au());
        aSG.put(AdGlobalConfigInfo.CycleAggregationInfo.class, new Cdo());
        aSG.put(AdMatrixInfo.RotateDegreeInfo.class, new la());
        aSG.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new du());
        aSG.put(AdInfo.RewardRetryTaskInfo.class, new kv());
        aSG.put(AdInfo.NativeAdInfo.class, new iw());
        aSG.put(AdProductInfo.SpikeInfo.class, new lw());
        aSG.put(com.kwad.sdk.commercial.i.b.class, new ba());
        aSG.put(com.kwad.sdk.wrapper.l.a.C0541a.class, new ml());
        aSG.put(AdMatrixInfo.InnerEcAuthInfo.class, new gj());
        aSG.put(com.kwad.sdk.commercial.b.b.class, new bo());
        aSG.put(com.kwad.sdk.utils.b.a.class, new ho());
        aSG.put(AdMatrixInfo.class, new am());
        aSG.put(AdInfo.AdRewardInfo.class, new aq());
        aSG.put(com.kwad.sdk.commercial.a.b.class, new bk());
        aSG.put(PhotoInfo.class, new jx());
        aSG.put(AdInfo.AdInsertScreenInfo.class, new z());
        aSG.put(HttpDnsInfo.IpInfo.class, new hb());
        aSG.put(AdInfo.CallBackStrategyInfo.class, new ci());
        aSG.put(ABParams.class, new a());
        aSG.put(AdMatrixInfo.RewardVideoInteractInfo.class, new kw());
        aSG.put(FeedSlideConf.class, new ey());
        aSG.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new ek());
        aSG.put(AdInfo.MaterialSize.class, new il());
        aSG.put(AdVideoPreCacheConfig.class, new bb());
        aSG.put(AdMatrixInfo.ShakeInfo.class, new lk());
        aSG.put(AdStyleInfo.FeedAdInfo.class, new et());
        aSG.put(AdMatrixInfo.EndCardInfo.class, new ej());
        aSG.put(AdLabelImpl.class, new ab());
        aSG.put(HttpDnsInfo.class, new gd());
        aSG.put(AdMatrixInfo.AggregationCardInfo.class, new be());
        aSG.put(AdInfo.NativeAdShakeInfo.class, new iy());
        aSG.put(AdMatrixInfo.SplashInfo.class, new mb());
        aSG.put(SplashExtraDataImpl.class, new ma());
        aSG.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new oi());
        aSG.put(AdMatrixInfo.TemplateData.class, new nc());
        aSG.put(PhotoInfo.BaseInfo.class, new by());
        aSG.put(AdMatrixInfo.StyleInfo.class, new ms());
        aSG.put(LiveInfo.LiveStreamPlayCDNNode.class, new ie());
        aSG.put(PhotoInfo.VideoInfo.class, new ns());
        aSG.put(SceneImpl.class, new lj());
        aSG.put(AdMatrixInfo.SplashSlideInfo.class, new mi());
        aSG.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new ky());
        aSG.put(LiveInfo.User.class, new np());
        aSG.put(AdMatrixInfo.ComponentParam.class, new cu());
        aSG.put(com.kwad.sdk.commercial.f.b.class, new fx());
        aSG.put(WebViewLoadMsg.class, new oh());
        aSG.put(AdProductInfo.class, new ap());
        aSG.put(StatusInfo.SplashAdInfo.class, new ly());
        aSG.put(AdInfo.AdConversionInfo.class, new m());
        aSG.put(com.kwad.sdk.h.a.b.class, new jp());
        aSG.put(AdMatrixInfo.StyleComponentInfo.class, new mr());
        aSG.put(com.kwad.sdk.wrapper.l.a.class, new oj());
        aSG.put(AdStatusInfo.class, new at());
        aSG.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new ia());
        aSG.put(com.kwad.sdk.core.h.a.C0514a.class, new mw());
        aSG.put(VideoPlayerStatus.class, new nx());
        aSG.put(AdMatrixInfo.RewardVideoTaskInfo.class, new kx());
        aSG.put(AdInfo.AdDrawInfo.class, new t());
        aSG.put(AdInfo.AdTrackInfo.class, new ay());
        aSG.put(AdStyleInfo.class, new av());
        aSG.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new ij());
        aSG.put(com.kwad.sdk.commercial.c.a.class, new ca());
        aSG.put(AdMatrixInfo.FullScreenInfo.class, new fj());
        aSG.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new c());
        aSG.put(AdInfo.DownloadSafeInfo.class, new ec());
        aSG.put(AdMatrixInfo.SplashEndCardTKInfo.class, new lz());
        aSG.put(AdMatrixInfo.DownloadTexts.class, new ee());
        aSG.put(AdInfo.AdSplashInfo.class, new as());
        aSG.put(AdLinkMonitorMsg.class, new ac());
        aSG.put(HybridLoadMsg.class, new ge());
        aSG.put(AdInfo.UnDownloadRegionConf.class, new nl());
        aSG.put(com.kwad.sdk.h.a.a.class, new jo());
        aSG.put(StatusInfo.class, new mp());
        aSG.put(com.kwad.sdk.commercial.d.b.class, new q());
        aSG.put(com.kwad.sdk.commercial.e.b.class, new dr());
        aSG.put(AdMatrixInfo.CycleAggregateInfo.class, new dn());
        aSG.put(AdMatrixInfo.PreLandingPageTKInfo.class, new kg());
        aSG.put(com.kwad.sdk.core.network.i.class, new ji());
        aSG.put(AdInfo.AdBaseInfo.class, new j());
        aSG.put(AdInfo.SlideConvertInfo.class, new ls());
        aSG.put(AdMatrixInfo.BottomBannerInfo.class, new cg());
        aSG.put(AdMatrixInfo.AdInteractionInfo.class, new aa());
        aSG.put(LiveInfo.class, new hw());
        aSG.put(TemplateConfig.class, new na());
        aSG.put(AdMatrixInfo.SlideInfo.class, new lt());
        aSG.put(com.kwad.sdk.commercial.smallApp.b.class, new lv());
        aSG.put(com.kwad.sdk.commercial.i.a.C0500a.class, new nh());
        aSG.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new dq());
        aSG.put(AdCouponReceiveParam.class, new p());
        aSG.put(AdGlobalConfigInfo.class, new w());
        aSG.put(CouponInfo.class, new dh());
        aSG.put(AdMatrixInfo.NeoVideoInfo.class, new jg());
        aSG.put(AdMatrixInfo.Styles.class, new mt());
        aSG.put(LiveInfo.CoverUrlCdn.class, new dk());
        aSG.put(AdMatrixInfo.RotateInfo.class, new lb());
        aSG.put(com.kwad.sdk.core.report.j.class, new el());
        aSG.put(LiveDetailReward.class, new hu());
        aSG.put(AdInfo.AdMaterialInfo.class, new al());
        aSG.put(com.kwad.sdk.commercial.convert.b.class, new n());
        aSG.put(com.kwad.sdk.core.request.model.f.class, new my());
        aSG.put(AdInfo.AdBannerInfo.class, new i());
        aSG.put(com.kwad.sdk.core.request.model.b.class, new dv());
        aSG.put(com.kwad.sdk.core.threads.d.class, new ne());
        aSG.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new dt());
        aSG.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new ef());
        aSG.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new jv());
        aSG.put(AdInfo.UnDownloadConf.class, new nk());
        aSG.put(com.kwad.sdk.commercial.d.c.class, new r());
        aSG.put(AdInfo.SmallAppJumpInfo.class, new lu());
        aSG.put(AdInfo.AdAggregateInfo.class, new h());
        aSG.put(AdInfo.H5Config.class, new fu());
        aSG.put(AdGlobalConfigInfo.RefreshToken.class, new kl());
        aSG.put(AdMatrixInfo.InterstitialCardInfo.class, new gx());
        aSG.put(AdStyleInfo.PlayEndInfo.class, new ka());
        aSG.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new ds());
        aSG.put(AdMatrixInfo.ComponentTemplateInfo.class, new cv());
        aSG.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new bc());
        aSG.put(LiveInfo.User.HeadUrl.class, new fz());
        aSG.put(AdMatrixInfo.InstalledActivateInfo.class, new gt());
        aSG.put(com.kwad.sdk.core.network.j.class, new jj());
        aSG.put(AdMatrixInfo.ActionBarInfoNew.class, new d());
        aSG.put(NativeAdExtraDataImpl.class, new iv());
        aSG.put(AdInfo.RewardFraudVerifyInfo.class, new kq());
        aSG.put(LiveInfo.CoverThumbnailUrl.class, new dj());
        aSG.put(URLPackage.class, new ni());
        aSG.put(AdMatrixInfo.SplashPlayCardTKInfo.class, new me());
        aSG.put(AdInfo.AdvertiserInfo.class, new bd());
        aSG.put(AdInfo.FullScreenVideoInfo.class, new fk());
        aSG.put(SDKInitMsg.class, new lf());
        aSG.put(AdMatrixInfo.NativeMatrixAdInfo.class, new jb());
        aSG.put(AdInfo.PlayableStyleInfo.class, new ke());
        aSG.put(AdMatrixInfo.DynamicAdStyleInfo.class, new ei());
        aSG.put(com.kwad.sdk.commercial.h.a.class, new ih());
        aSG.put(AdInfo.AdPreloadInfo.class, new ao());
        aSG.put(AdInfo.AdShowVideoH5Info.class, new ar());
        aSG.put(com.kwad.sdk.core.threads.b.class, new nd());
        aSG.put(AdStyleInfo.ExtraDisplayInfo.class, new er());
        aSG.put(AdGlobalConfigInfo.NeoScanAggregationSceneInfo.class, new je());
        aSG.put(StatusInfo.NativeAdStyleControl.class, new iz());
        aSG.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new ir());
        aSG.put(PageInfo.class, new js());
        aSG.put(WebViewCommercialMsg.class, new og());
        aSG.put(com.kwad.sdk.core.config.d.class, new jq());
        aSG.put(AdMatrixInfo.FeedInfo.class, new ev());
        aSG.put(ImageLoaderInfo.class, new gh());
        aSG.put(AdInfo.class, new y());
        aSG.put(AdInfo.CutRuleInfo.class, new dm());
        aSG.put(TKAdLiveShopItemInfo.class, new mu());
        aSG.put(AdMatrixInfo.MatrixTemplate.class, new in());
        aSG.put(AdStyleInfo.PlayDetailInfo.class, new jy());
        aSG.put(AdTemplate.class, new ax());
        aSG.put(LiveRewardInfo.class, new ib());
        aSG.put(AdMatrixInfo.MatrixTag.class, new im());
        aSG.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new g());
        aSG.put(StatusInfo.NativeAdRequestInfo.class, new ix());
        aSG.put(AdMatrixInfo.AdDataV2.class, new s());
        Md();
    }

    @ForInvoker(methodId = "registerHolder")
    private static void Md() {
        cw.Md();
        cx.Md();
        cy.Md();
        cz.Md();
        da.Md();
        db.Md();
        dc.Md();
        dd.Md();
        de.Md();
        df.Md();
        fc.Md();
        fd.Md();
        fe.Md();
        ff.Md();
        fg.Md();
        fh.Md();
    }

    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> Me() {
        return aSG;
    }

    public static com.kwad.sdk.core.d getHolder(Class<? extends com.kwad.sdk.core.response.a.a> cls) {
        return aSG.get(cls);
    }
}
